### ISSUE TITLE
Android 10, magisk, systemless hosts resetting

### ISSUE THREAD

**Issue by kbirger** [AdAway/AdAway#1253]
**Describe the bug**
The ads come back and Systemless hosts setting turns itself off.

**To Reproduce**
- Install magisk 19.3 on Android 10
- set up systemless hosts module
- install adaway
- set systemless hosts
- download hosts file, 
- reboot

Eventually (I don't think it even takes another reboot,but maybe?) Ads come back,and I find the Systemless hosts setting cleared.

If I set it again,and download a new hosts file, then reboot, it works for a while longer.

**Expected behavior**
Set and forget like it worked on Android 9 with adaway 4.2.5 (I think?)

**Device**
 - AdAway version: 4.2.9
 - Device: pixel 2016 sailfish
 - Android version: Android 10
 - Root version magisk 19.3

**Comment by eturk1** [comment]
On my Pixel 2 XL w/Android 10 "enable systemless mode" is not sticky either.

**Comment by DizzyThermal** [comment]
Experiencing the same issue: Pixel 2 XL w/ Android 10 and Magisk 19.4

**Comment by Avil** [comment]
+1. Same issue, same environment as above, Pixel 2 walleye w/ Magisk 19.4 and systemless module. "Systemless hosts" toggle in settings also is unresponsive at times - not sure if related.

```
09-23 06:06:07.034 E/AdAway  (18385): Failed to update hosts file.
09-23 06:06:07.034 E/AdAway  (18385): org.adaway.model.hostsinstall.HostsInstallException: The symlink to the hosts file target is missing.
09-23 06:06:07.034 E/AdAway  (18385): 	at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:442)
09-23 06:06:07.034 E/AdAway  (18385): 	at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2$HostsInstallViewModel(HostsInstallViewModel.java:124)
09-23 06:06:07.034 E/AdAway  (18385): 	at org.adaway.ui.home.-$$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2)
09-23 06:06:07.034 E/AdAway  (18385): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-23 06:06:07.034 E/AdAway  (18385): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-23 06:06:07.034 E/AdAway  (18385): 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by Motophan** [comment]
AdAway version: 4.2.9
Device: pixel 2018 crosshatch
Android version: Android 10 september C3 build
Root version magisk 19.3 

OP your phone unrooted itself because a system update rewrote the /boot partition. 
Cant do symlinks to /system/etc/hosts because its not existing or incorrect 
App claims that there is not enough space for the host file, but its because the target isnt available

I am unfamiliar with how hosts work in android 10

**Comment by kbirger** [comment]
My phone definitely didn't unroot itself, and this doesn't have to do with the updating process, because everything still works until I have to do a reboot, and even then I have to just re-enable Systemless hosts, and everything works.

**Comment by PerfectSlayer** [comment]
Hi @kbirger 

First, thanks for your contribution. I finally get my hand on an Android 10 device so I can now test compatibility with this version.

About the steps you describe, I have some questions:
* Do you reboot after  _setting up systemless hosts module_ and before _downloading hosts file_?
* What do you call _set systemless hosts_?

Thanks for you help troubleshooting this kind of issue.

**Comment by kbirger** [comment]
Hi @PerfectSlayer 

Sorry if I was unclear. I am referring to preferences > Enable systemless mode.

- launch adaway
- enable systemless mode
- download hosts
- reboot

Everything works- hosts file blocks ads

- do some work
- reboot
- systemless mode is cleared
- hosts file doesn't take affect anymore

**Comment by PerfectSlayer** [comment]
Okay. I better understand now.

Let's try something:
1. First, disable and forgot about the _systemless mode_ option in the AdAway app
2. Enable the _systemless mode_ in Magisk
3. Reboot
4. Install / apply hosts file from AdAway
5. Reboot or do anything to test that it persists.

I think the systemless script bundled in AdAway is obsolete.
Now, Magisk provides an option to enable the related module.

Don't forget to report so I will decide if I remove it from the app (to prevent Magisk users to be confused). Thanks!

**Comment by kbirger** [comment]
Have you tried this? The reason I searched and discovered this feature is because I was getting an error with just that magisk module. It was a write access error. 

What should my hosts file path be set to, then? I'm not entirely sure how the Systemless stuff works to be honest.

I have since that original time reinstalled magisk, so I don't think it would be an issue with the module.

**Comment by kbirger** [comment]
Just tried it again. 

- Android 10
- Magisk (systemless hosts module enabled)
- adaway target hosts file: /system/etc/hosts
- reboot
- verify hosts file not applied
- open adaway
- observe that app reports hosts as not being applied, systemless mode is off
- press [enable ad blocking]
- observe that app downloads and builds hosts file
- but then errors: **Remount failed** Remounting the partition as read/write failed! ..etc..

**Comment by williamentropy** [comment]
i am having this same issue (pixel 2018, just updated to android 10 and re-rooted with magisk 20 yesterday) and so far seem to be having the same results as @kbirger with the only exception:
> but then errors: Remount failed Remounting the partition as read/write failed! ..etc..

i get a different error:
> symlink missing: symlink from your target /system/etc/hosts is not existing or incorrect [...] do you want to try creating symlink?

if i select "no", nothing happens. if i select "yes", it re-enables the "systemless host" option in adaway preferences and i get a new toast:
> symlink creation failed [and a long error message about S-ON and creating the symlink yourself]

happy to provide any further information to assist...

**Comment by eturk1** [comment]
Errors from steps in your post:
![Screenshot_20191023-195002](https://user-images.githubusercontent.com/525280/67449490-32c02780-f5cf-11e9-92ed-2fed5a1f9f41.png)



> Okay. I better understand now.
> 
> Let's try something:
> 
> 1. First, disable and forgot about the _systemless mode_ option in the AdAway app
> 2. Enable the _systemless mode_ in Magisk
> 3. Reboot
> 4. Install / apply hosts file from AdAway
> 5. Reboot or do anything to test that it persists.
> 
> I think the systemless script bundled in AdAway is obsolete.
> Now, Magisk provides an option to enable the related module.
> 
> Don't forget to report so I will decide if I remove it from the app (to prevent Magisk users to be confused). Thanks!

**Comment by PerfectSlayer** [comment]
@kbirger Thanks for your test. The Magisk module should be the right way to do systemless hosts file modification. The AdAway bundled script is too old I think.

About target file, the default settings is right: `/system/etc/hosts`.

About _systemless mode_ being disabled in AdAway, _it's normal_. You should now use the Magisk module instead. I was thinking last about a way to find if the module is installed  and update the AdAway UI accordingly (but for the moment, please forget the settings).

Then you got a _Remount error_ which should be an AdAway bug because your configuration looks good.


@williamentropy Thanks for you help. What did you use as target? It looks like you are not using the default one.

Clearing data could have reset the target settings. It might explain it works now.

@eturk1 Thanks for the log.

For all having errors while applying hosts, could you provide me some logcat with:
1. Check _Enable verbose logging_ from settings,
2. Kill and restart the app,
3. Try to apply hosts file,
4. Paste here a logcat.

I am only interested by the AdAway app and RootCommands shell commands logs. You can remove any other app or potential personal information from the logs 😅

**Comment by PerfectSlayer** [comment]
c6afddcb4174284767ce861e87ade4050a2ab48a should fix the _systemless mode_ activation status in AdAway settings.

**Comment by eturk1** [comment]
verbose log from trying to enable hosts:
![Screenshot_20191024-121258](https://user-images.githubusercontent.com/525280/67519023-d3a7f480-f65a-11e9-92b6-1134b52f84ef.png)

**Comment by PerfectSlayer** [comment]
@eturk1 Thanks! Could you look for `RootCommands` tag instead of `AdAway`? It should display run shell commands and their status.

About Chrome, don't forget to disable data saver feature :wink:

**Comment by eturk1** [comment]
how about a RootCommands fail just before Adaway fail?

![Screenshot_20191024-232706](https://user-images.githubusercontent.com/525280/67548284-4eeac400-f6b6-11e9-97be-1bdfa3c018bf.png)

**Comment by eturk1** [comment]
Yes, data saver off. 
Adaway was blocking ads, upgrade to Android 10 from 9 (not fresh install) and that broke AdAway

> @eturk1 Thanks! Could you look for `RootCommands` tag instead of `AdAway`? It should display run shell commands and their status.
> 
> About Chrome, don't forget to disable data saver feature 😉

**Comment by PerfectSlayer** [comment]
> how about a RootCommands fail just before Adaway fail?

Yes, you should have a lot of commands under the `RootCommands` tag and one must fail. Then AdAway throws the error.

Could you export the full logcat as text? Because I can't see all the commands nor understand what the `Remounter` tries to do?

For the record, I tried the latest Android 10 version with Magisk stable (v20) and it works well. I really need this kind of logs in order to understand what can go wrong on your devices. Thanks!

**Comment by williamentropy** [comment]
> Thanks for you help. What did you use as target? It looks like you are not using the default one.

before i found this thread, i had tried setting it to another of the selections, but i set it back to `/system/etc/hosts` when those didn't work either. that's where it is currently, and when i `adb shell` in, i can see the hosts file at that location has all the adaway entries in it.

**Comment by eturk1** [comment]
dragged & dropped 155kb txt file into github editor but "something went wrong".
can I DM it to you somehow?

> > how about a RootCommands fail just before Adaway fail?
> 
> Yes, you should have a lot of commands under the `RootCommands` tag and one must fail. Then AdAway throws the error.
> 
> Could you export the full logcat as text? Because I can't see all the commands nor understand what the `Remounter` tries to do?
> 
> For the record, I tried the latest Android 10 version with Magisk stable (v20) and it works well. I really need this kind of logs in order to understand what can go wrong on your devices. Thanks!

**Comment by PerfectSlayer** [comment]
You can DM it using Twitter at https://twitter.com/HardCoding
If you don't use Twitter, tell me so I can find another way. 

Edit: https://pastebin.com/ could also be an option to upload the logcat.

**Comment by eturk1** [comment]
ah
https://pastebin.com/ScAS9TtV

> You can DM it using Twitter at https://twitter.com/HardCoding
> If you don't use Twitter, tell me so I can find another way.
> 
> Edit: https://pastebin.com/ could also be an option to upload the logcat.

**Comment by PerfectSlayer** [comment]
Ok, thanks for the log! 👍  I can see the reason of AdAway error for your device.

The app list your mount points:
```
Sending command(s): cat /proc/mounts 2>&1
ID: 0, Output: /dev/root / ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: tmpfs /sbin tmpfs rw,seclabel,relatime,mode=755 0 0
ID: 0, Output: /sbin/.magisk/block/system_root /sbin/.magisk/mirror/system_root ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /sbin/.magisk/block/vendor /sbin/.magisk/mirror/vendor ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /sbin/.magisk/block/data /sbin/.magisk/mirror/data ext4 rw,seclabel,relatime,noauto_da_alloc,resgid=1065,errors=panic,stripe=2,data=ordered 0 0
ID: 0, Output: /sbin/.magisk/block/data /sbin/.magisk/modules ext4 rw,seclabel,relatime,noauto_da_alloc,resgid=1065,errors=panic,stripe=2,data=ordered 0 0
ID: 0, Output: tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,mode=755 0 0
ID: 0, Output: devpts /dev/pts devpts rw,seclabel,relatime,mode=600 0 0
ID: 0, Output: none /dev/cpuctl cgroup rw,nosuid,nodev,noexec,relatime,cpu 0 0
ID: 0, Output: none /dev/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent 0 0
ID: 0, Output: none /dev/stune cgroup rw,nosuid,nodev,noexec,relatime,schedtune 0 0
ID: 0, Output: adb /dev/usb-ffs/adb functionfs rw,relatime 0 0
ID: 0, Output: mtp /dev/usb-ffs/mtp functionfs rw,relatime 0 0
ID: 0, Output: ptp /dev/usb-ffs/ptp functionfs rw,relatime 0 0
ID: 0, Output: proc /proc proc rw,relatime,gid=3009,hidepid=2 0 0
ID: 0, Output: sysfs /sys sysfs rw,seclabel,relatime 0 0
ID: 0, Output: selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
ID: 0, Output: debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
ID: 0, Output: tracefs /sys/kernel/debug/tracing tracefs rw,seclabel,relatime 0 0
ID: 0, Output: pstore /sys/fs/pstore pstore rw,seclabel,relatime 0 0
ID: 0, Output: tmpfs /mnt tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
ID: 0, Output: /data/media /mnt/runtime/default/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal 0 0
ID: 0, Output: /data/media /mnt/runtime/read/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal 0 0
ID: 0, Output: /data/media /mnt/runtime/write/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal 0 0
ID: 0, Output: /data/media /mnt/runtime/full/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal 0 0
ID: 0, Output: tmpfs /apex tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755 0 0
ID: 0, Output: /dev/block/dm-2 /apex/com.android.tzdata@291602000 ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/dm-2 /apex/com.android.tzdata ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/dm-3 /apex/com.android.media.swcodec@291700100 ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/dm-3 /apex/com.android.media.swcodec ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/dm-4 /apex/com.android.media@291602000 ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/dm-4 /apex/com.android.media ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/dm-5 /apex/com.android.conscrypt@291602000 ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/dm-5 /apex/com.android.conscrypt ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/dm-6 /apex/com.android.resolv@291602000 ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/dm-6 /apex/com.android.resolv ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/loop7 /apex/com.android.runtime@1 ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/loop7 /apex/com.android.runtime ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/loop8 /apex/com.android.apex.cts.shim@1 ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/loop8 /apex/com.android.apex.cts.shim ext4 ro,dirsync,seclabel,nodev,noatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: /dev/block/platform/soc/1da4000.ufshc/by-name/persist /persist ext4 rw,seclabel,nosuid,nodev,noatime,data=ordered 0 0
ID: 0, Output: /dev/block/dm-0 /vendor ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
ID: 0, Output: none /acct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0
ID: 0, Output: none /config configfs rw,nosuid,nodev,noexec,relatime 0 0
ID: 0, Output: /dev/block/platform/soc/1da4000.ufshc/by-name/metadata /metadata ext4 rw,sync,seclabel,nosuid,nodev,noatime,discard,data=ordered 0 0
ID: 0, Output: /dev/block/platform/soc/1da4000.ufshc/by-name/modem_b /firmware vfat ro,context=u:object_r:firmware_file:s0,relatime,uid=1000,gid=1000,fmask=0337,dmask=0227,codepage=437,iocharset=iso8859-1,shortname=lower,errors=remount-ro 0 0
ID: 0, Output: /dev/block/dm-1 /data ext4 rw,seclabel,nosuid,nodev,noatime,noauto_da_alloc,resgid=1065,errors=panic,stripe=2,data=ordered 0 0
ID: 0, Output: tmpfs /storage tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
ID: 0, Output: /data/media /storage/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal 0 0
ID: 0, Output: tmpfs /storage/self tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
Command 0 finished.
```

The only matching mount point for `/system/etc/hosts` is ` /dev/root /`.
So it then tries to mount `/` as RW:

```
Sending command(s): busybox mount -o remount,rw /dev/root / 2>&1
toolbox mount -o remount,rw /dev/root / 2>&1
mount -o remount,rw /dev/root / 2>&1
/system/bin/toolbox mount -o remount,rw /dev/root / 2>&1
toybox mount -o rw,remount /dev/root / 2>&1

ID: 1, Output: /system/bin/sh: <stdin>[5]: busybox: inaccessible or not found
ID: 1, Output: mount: no such tool
ID: 1, Output: '/dev/root' is read-only
ID: 1, Output: mount: no such tool
ID: 1, Output: '/dev/root' is read-only
Command 1 finished.
```

Some tools fails (and it is normal, I try a lot of tools for a maximum compatibility) and some work as expected with the following output: `'/dev/root' is read-only`.
As you are on Android 10, you can't remount this mount point.

That leads us to the main issue, **why don't you have the following mount point in your mounts**?
`/sbin/.magisk/block/data on /system/etc/hosts type ext4 (rw,seclabel,relatime,noauto_da_alloc,resgid=1065,errors=panic,stripe=4096,data=ordered)`
As you could guess, this mount point is created by the Magisk systemless hosts module.

Could you check it is well enabled and you reboot your device since?
Because without it, AdAway won't be able to write hosts file (resulting the error you have in the AdAway UI).

**Comment by eturk1** [comment]
LMAO
Solved!  No more stinkin' ads.

Noticed the busybox error in the last log section in your post. Didn't think adaway needed but I'd add it anyway, this time with Magisk module. Welllllll... I noticed that the systemless module seemed to not be installed. Check it. Bam!

Looks like Magisk was just downloading but not installing the systemless module. Maybe a v20 or A10 issue. Never had to manually install after tapping in settings before. Whatever, I'm ad-free. 

I'm a man of my word and sent you $10 for a beer @PerfectSlayer. Thanks for jumping in to get me thinking about solving this. 

Make sure systemless module has a check mark, is actually installed:
<img width="288" alt="Screenshot_20191027-180947" src="https://user-images.githubusercontent.com/525280/67648682-a5911180-f8f3-11e9-8ab4-1cd724af29e8.png">


> Ok, thanks for the log! 👍 I can see the reason of AdAway error for your device.

**Comment by PerfectSlayer** [comment]
Thank for your feedback and your donation 🙏 

I will keep gathering issue about Android 10 in order to find the more common issues.
I already fixed the _systemless hosts_ Magisk module detection so I think I will make a quick release about it.

@kbirger @DizzyThermal @Motophan Have you try theses step: https://github.com/AdAway/AdAway/issues/1253#issuecomment-546039484 ? If yes, did it fixed your case? If no, could you post a logcat with debug logging enabled? Thanks all!

**Comment by eturk1** [comment]
Well that's a bummer! :(
Lasted a day & ads are back.
AdAway still shows "enabled". I was seeing grey boxes or empty areas where ads would be but today they are showing again.

**Comment by PerfectSlayer** [comment]
Could you check the content of the hosts file? (to check if it is resetting as previously)

**Comment by PerfectSlayer** [comment]
Version 4.3.0 is out. Let me know if you still encounter some bugs.

**Comment by aagha** [comment]
Hi @PerfectSlayer - I'm having this issue as well.

Pixel 3a, Magisk (Systemless module active):

![image](https://user-images.githubusercontent.com/5522103/74597773-a6bc8a80-5019-11ea-9ed4-69f51146d133.png)

The error manifests itself as:

- Fresh install (previously cleared storage/cache)
- Install from F-droid
- Grant root
- Try to enable Ad-blocking
- Download hosts files

Then:

![image](https://user-images.githubusercontent.com/5522103/74597787-e08d9100-5019-11ea-8fa6-4b63f413db0d.png)

Try to get more info:

![image](https://user-images.githubusercontent.com/5522103/74597790-e7b49f00-5019-11ea-90db-24ddc26feddb.png)

Checked the hosts file:

![image](https://user-images.githubusercontent.com/5522103/74597793-f00cda00-5019-11ea-8912-75694e2399c3.png)

Per the comment above, here is the logcat:

[adaway_20200215.txt](https://github.com/AdAway/AdAway/files/4209258/adaway_20200215.txt)

**Comment by PerfectSlayer** [comment]
Hello @aagha 

According the logcat, it seems you changed the destination of the hosts file to `/data/data/hosts`:
```
02-15 17:33:37.509 18977 19011 D AdAway  : symlink: null; target: /data/data/hosts
02-15 17:33:37.509 18977 19011 E AdAway  : Failed to update hosts file.
02-15 17:33:37.509 18977 19011 E AdAway  : org.adaway.model.hostsinstall.HostsInstallException: The symlink to the hosts file target is missing.
02-15 17:33:37.509 18977 19011 E AdAway  : 	at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:442)
02-15 17:33:37.509 18977 19011 E AdAway  : 	at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2$HostsInstallViewModel(HostsInstallViewModel.java:124)
02-15 17:33:37.509 18977 19011 E AdAway  : 	at org.adaway.ui.home.-$$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2)
02-15 17:33:37.509 18977 19011 E AdAway  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-15 17:33:37.509 18977 19011 E AdAway  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-15 17:33:37.509 18977 19011 E AdAway  : 	at java.lang.Thread.run(Thread.java:919)
```

Could you set it back to the default settings? Then it could use the Magsik systemless mode.

**Comment by aagha** [comment]
Hi @PerfectSlayer 

I never did that (used an editor on my phone to change any paths). Not sure how that happened.

How would I change it to the default? Edit this file from AdAway?

![image](https://user-images.githubusercontent.com/5522103/74693465-cd58fd80-51a0-11ea-8652-de4050d824d1.png)

What do I change?

**Comment by Kronopt** [comment]
You could try downloading a terminal emulator from the store and creating the symlink yourself (you will have to grant it root permissions).

In my phone the hosts file is located at `/system/etc/hosts`, but I believe that is not standard, so you might have to search for the actual location of the hosts file on your device.

Assuming you maintain the `/data/data/hosts` as your hosts file location (the logcat error shows that as your location, so if nothing changes, this should work):
```sh
$ ln -s /system/etc/hosts /data/data/hosts
```
should create a symlink of your hosts file in the `/data/data/` folder.

I recommend:
* Unloading the Systemless Hosts Magisk module
* Running this command
* Restart
* Re-enable Systemless Hosts Magisk module
* Restart
* Test AdAway

**Comment by PerfectSlayer** [comment]
I would not recommend to use symlink if you have Magisk installed. The usual way is to enable Systemless mode from Magisk and use the default `/system/etc/hosts` in `Target hosts file` setting from AdAway app.

**Comment by aagha** [comment]
I tried that @PerfectSlayer. That didn't work for me, which is why I posted:

https://github.com/AdAway/AdAway/issues/1253#issuecomment-587211444

**Comment by PerfectSlayer** [comment]
Okay so can you post a logcat with the default target settings?

**Comment by aagha** [comment]
> Okay so can you post a logcat with the default target settings?

It's at the bottom of: https://github.com/AdAway/AdAway/issues/1253#issuecomment-586659239

**Comment by PerfectSlayer** [comment]
Negative. This logcat tells you set the target to `/data/data/hosts`.

```
02-15 17:33:39.005 18977 18977 D RootCommands: Remounting /system/etc/hosts as rw
02-15 17:33:39.005 18977 18977 D RootCommands: [discard, flush_merge, fsync_mode=nobarrier, active_logs=6, rw, user_xattr, relatime, mode=adaptive, seclabel, no_heap, alloc_mode=default, inline_xattr, lazytime, acl, reserve_root=25554, extent_cache, resgid=1065, background_gc=on, inline_data, inline_dentry, resuid=0] AND rw
02-15 17:33:39.005 18977 18977 D RootCommands: [discard, flush_merge, fsync_mode=nobarrier, active_logs=6, rw, user_xattr, relatime, mode=adaptive, seclabel, no_heap, alloc_mode=default, inline_xattr, lazytime, acl, reserve_root=25554, extent_cache, resgid=1065, background_gc=on, inline_data, inline_dentry, resuid=0]
02-15 17:33:39.005 18977 19586 D RootCommands: Sending command(s): rm -f /system/etc/hosts 2>&1
02-15 17:33:39.005 18977 19586 D RootCommands: ln -s /data/data/hosts /system/etc/hosts 2>&1
02-15 17:33:39.005 18977 19586 D RootCommands: chcon u:object_r:system_file:s0 /data/data/hosts 2>&1
02-15 17:33:39.005 18977 19586 D RootCommands: chown 0:0 /data/data/hosts 2>&1
02-15 17:33:39.005 18977 19586 D RootCommands: chmod 644 /data/data/hosts 2>&1
02-15 17:33:39.021 18977 19587 D RootCommands: ID: 0, Output: rm: /system/etc/hosts: Read-only file system
02-15 17:33:39.039 18977 19587 D RootCommands: ID: 0, Output: ln: cannot create symbolic link from '/data/data/hosts' to '/system/etc/hosts': File exists
02-15 17:33:39.057 18977 19587 D RootCommands: ID: 0, Output: chcon: /data/data/hosts: No such file or directory
02-15 17:33:39.070 19584 19584 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
02-15 17:33:39.073 19584 19584 I AndroidRuntime: Using default boot image
02-15 17:33:39.073 19584 19584 I AndroidRuntime: Leaving lock profiling enabled
02-15 17:33:39.078 18977 19587 D RootCommands: ID: 0, Output: chown: /data/data/hosts: No such file or directory
02-15 17:33:39.100 18977 19587 D RootCommands: ID: 0, Output: chmod: /data/data/hosts: No such file or directory
02-15 17:33:39.101 18977 19587 D RootCommands: Command 0 finished.
```

**Comment by aagha** [comment]
OK, how/where do I do that?

**Comment by PerfectSlayer** [comment]
From app, open menu, go to `Preferences` then tap `Target hosts file` and select the first choice `/system/etc/hosts`.

**Comment by aagha** [comment]
@PerfectSlayer Though I'd tried it before, uninstalling the app, re-installingit, and changing the Target hosts file has gotten AdAway to work again. I don't have any idea why.

**Comment by PerfectSlayer** [comment]
Glad it's working again.

**Comment by klodoma** [comment]
After 20 minutes of try and error, UnInstall/Re-install the latest version of AdAway solves this issue. I have enabled Systemless mode in Magisk, not sure if that plays a role though.
