### ISSUE TITLE
Doubt with new version

### ISSUE THREAD

**Issue by gallegonovato** [AdAway/AdAway#1801]
Good afternoon:

First of all I want to thank you for all your efforts and help in making adaway indispensable.  At least for me.

It turns out that in a host, more specifically:

https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext

Puts me right under: Needs update for - 6 minutes

I already gave it a few updates and it was lowering the time it needed to be updated.  It used to be - 53 minutes.  And it always detects and installs the host. Since it comes out on the main screen the blue faeces and after installing the things I give it to reboot.

I checked the time of my device and it is fine as well as the day.  I don't know if I should try to remove and re-install that host, I don't know what you recommend.

And the last question is if you'll let me.  It turns out that a family member's phone has it installed from fdroid.  And of course when you download the new version of github.  It tells him that it hasn't been installed.  Since I understand that something has to be different between github and fdroid.  That's why I wanted to ask you if the new version is going to be uploaded to fdroid.  Or fdroid will bring it out.  Or I tell him to write down the hosts he has and uninstall the one he has.  And install the new version of github?.

A hug and thanks for your help.

Pd: Thank you for your mention in the new update.  I mean mentioning me on https://github.com/AdAway/AdAway/releases/tag/v4.3.3 .  But I don't have any merit.  The credit goes to you for making such a good program or application.  I simply tried to help and I try to help in any way I can and do.  That I was able to help is the best thing for me.  I thank you sincerely for this :)

**Comment by PerfectSlayer** [comment]
Hello @gallegonovato 

The "minus xx minutes" issues was fixed here d9bf8b67755ede3aa5164b611830d05c9ea88715 but no new build ship it yet.

F-Droid and GitHub apk are not the same because they are not signed by the same certificate. F-Droid uses its own and does not share it and I can't use mine on F-Droid. You can freely move from one version to another if you export your settings, uninstall the app, install it from the other source then reimport your settings. The settings are also compatible between V4 and V5.

The V5 will be released on F-Droid once it's stable enough 😉

**Comment by gallegonovato** [comment]
Good afternoon @PerfectSlayer

Thank you very much for your help.  But sometimes I still have the same problem with that host site.  Tested on a different cell phone. 

A hug.

**Comment by PerfectSlayer** [comment]
I guess the negative time is only for few minutes. Never more than an hour?
Because I observed the server is not time sync and sometime has few minutes in advance compared to the world clock. I plan to apply a workaround for this case this weekend.

**Comment by gallegonovato** [comment]
Good afternoon:

I think the most he got was - 45 minutes.

That if you give it several times to check for updates and that it installs the updates every time, it lowers the time. It's getting good.

A hug. 

Pd: I don't know if you could look at the fault Adaway has with the turning of the automatic or manual screen of the mobile. If you have it always in horizontal, it doesn't happen. This happens in versions 4 and 5. And I don't know if, it can be done or is feasible, the suggestion I make at https://github.com/AdAway/AdAway/issues/1942 

Pd: I'm sorry to give you such a headache. I don't mean to, I'm just trying to help. The best I can. If you need help with translation or anything like that, don't hesitate to let me know.
