### ISSUE TITLE
VPN Reconnecting error 

### ISSUE THREAD

**Issue by rokahaal** [AdAway/AdAway#3130]
**Describe the bug**
Since I've updated my unrooted oneplus 9 pro to newest original android 12 OxygenOS adaway always show the VPN Reconnecting error message. 

**To Reproduce**
I don't know how to reproduce and I don't know if it is a problem of OxygenOS or of adaway. With previous Android 11 OxygenOS this error didn't occure. I've tried a clean install of adaway 5.11 including the VPN permissions but it doesn't work. 

**Screenshots**
![Screenshot_2022-01-27-11-31-59-90_0d8cecce28558e4d0a8cf6af1b99c74e](https://user-images.githubusercontent.com/10568618/151408662-88daaee1-8f29-40df-91da-5c985b16a7d9.jpg)
![Screenshot_2022-01-27-18-02-48-59_16f10d01b9d7140de773114faf80a66e](https://user-images.githubusercontent.com/10568618/151408666-4e7809f2-ae4e-45ee-a2d1-a03e3920cf64.jpg)

**Device**
 - AdAway version: 5.11
 - Device: OnePlus 9 Pro 
 - Android version: 12
 - Root version: unrooted VPN version

**Comment by maxreuben** [comment]
The error is also found in Pixel 6 using Android 12. To reproduce connect to another VPN, and then disconnect and try reconnecting to adaway through the quick settings icon. It says AdAway is starting then receives a notification saying VPN reconnecting error.

Workaround: reopen the AdAway app and disconnect and reconnect.

**Comment by WatermelonOof** [comment]
Same issue on my OP7T running Android 11.

**Comment by PerfectSlayer** [comment]
@maxreuben Yes, AdAway will loose the right to start a VPN and it needs to be `prepared` again.
I don't think I am allowed to start a UI from the quick settings to let the user accept it. I need to check this use case.

@rokahaal Is it the same issue you originally described?

**Comment by rokahaal** [comment]
> @maxreuben Yes, AdAway will loose the right to start a VPN and it needs to be `prepared` again. I don't think I am allowed to start a UI from the quick settings to let the user accept it. I need to check this use case.
> 
> @rokahaal Is it the same issue you originally described?

Last days I've tried some things. I found out that adaway is working on mobile network but loses VPN in my wifi. After changing from mobile to wifi adaway losing VPN after 20-30 sec. Disconnect and reconnect doesn't help. My wifi router is a AVM Fritzbox 6590. Maybe there is a problem in the connection between my oneplus and my wifi router. I've made a short video.

https://user-images.githubusercontent.com/10568618/152674318-5543b568-0440-485d-9a48-efa2f37344e5.mp4

**Comment by PerfectSlayer** [comment]
Oh yeah... So it should be a duplicate of #2154 

It's been months trying to fix it... [I spend 3 hours this morning again](67f6960336291a82c23a95a6ee6a19eca8272fd8) :(
Once I find a reliable solution to get it work, I could push the new VPN implementation.

**Comment by rokahaal** [comment]
> Oh yeah... So it should be a duplicate of #2154
> 
> It's been months trying to fix it... [I spend 3 hours this morning again](67f6960336291a82c23a95a6ee6a19eca8272fd8) :( Once I find a reliable solution to get it work, I could push the new VPN implementation.

Thank you for your efforts.  Issue 2154 is similar to this one.  But with error 2154 manual disconnection and reconnection still helped.  But with this issue here, no VPN connection can be established at all. Today I tried two other older wifi routers.  Adaway VPN worked on both routers  during the WiFi connection.  It seems that especially the current running fritzOS version 7.29 and above obviously has problems with VPN and Android 12.

**Comment by PerfectSlayer** [comment]
Did it help if you kill the app and restart it? 
I notice the app process sometimes keeps the reference to a broken VPN instance preventing to start another one until it is killed.

**Comment by rokahaal** [comment]
> Did it help if you kill the app and restart it? I notice the app process sometimes keeps the reference to a broken VPN instance preventing to start another one until it is killed.

Unfortunately that doesn't help.

https://user-images.githubusercontent.com/10568618/153068752-6d43d532-a526-464f-9ae1-bf84b0118d56.mp4

**Comment by PerfectSlayer** [comment]
Can you try this build? [AdAway-feat-vpn-220212.zip](https://github.com/AdAway/AdAway/files/8053117/AdAway-feat-vpn-220212.zip)
It is my personal build of the feature/vpn branch and I got good results for over a week (with cellular, wifi, airplane, captive portal, …).
It is signed with the GitHub release keys so you can install it over if you come from the GitHub installs.

Instruction:
- Backup the app settings from the settings menu (so you can revert if anything goes wrong),
- Install apk inside the zip (I was not allowed to attach an apk, only a zip file),
- Ensure Monitor connection is disbled from Se release keys so you can install it over if you come from the GitHub installs.

Instruction:
- Backup the app settings from the settings menu (so you can revert if anything goes wrong),
- Install apk inside the zip (I was not allowed tottings/VPN

If you still have issue, enable verbose logging from settings, restart the app, reproduce and post a logcat.
It will help to test and make this branch progress.

**Comment by rokahaal** [comment]
> Can you try this build? [AdAway-feat-vpn-220212.zip](https://github.com/AdAway/AdAway/files/8053117/AdAway-feat-vpn-220212.zip) It is my personal build of the feature/vpn branch and I got good results for over a week (with cellular, wifi, airplane, captive portal, …). It is signed with the GitHub release keys so you can install it over if you come from the GitHub installs.
> 
> Instruction:
> 
> * Backup the app settings from the settings menu (so you can revert if anything goes wrong),
> * Install apk inside the zip (I was not allowed to attach an apk, only a zip file),
> * Ensure Monitor connection is disbled from Se release keys so you can install it over if you come from the GitHub installs.
> 
> Instruction:
> 
> * Backup the app settings from the settings menu (so you can revert if anything goes wrong),
> * Install apk inside the zip (I was not allowed tottings/VPN
> 
> If you still have issue, enable verbose logging from settings, restart the app, reproduce and post a logcat. It will help to test and make this branch progress.

Thank you for the trial version. Unfortunately, there is no improvement with it. I have also written to the manufacturer of my router and asked them to take a look at the problem as well. Unfortunately the manufacturer can't find a bug in their firmware. I tried it on 3 other WiFi routers, with them adaway worked without any problems. On the cellular network as well. My current wifi router is the only one where it doesn't work.

**Comment by PerfectSlayer** [comment]
@rokahaal You can check the last test build I post on #2154. We made some interesting improvements.

**Comment by PerfectSlayer** [comment]
It should be fixed in the last beta. Feel free to report if it is not the case.

**Comment by rokahaal** [comment]
> It should be fixed in the last beta. Feel free to report if it is not the case.

I have now tested beta 6.0 for a few days. Unfortunately, adaway is still not stable in my WLAN. The VPN connection is terminated after a short time and cannot be restored. And adaway can no longer be stopped manually, it constantly tries to establish a VPN connection in the background, but this doesn't work.

**Comment by PerfectSlayer** [comment]
> it constantly tries to establish a VPN connection in the background, but this doesn't work

Could you enable verbose logging, restart the app, reproduce and share a logcat?
